Working IDAKLU standalone build and wheels
pybamm-team/pybammsolvers pull request #3
Opened 2024-09-25 13:31 UTC by santacodes

Got the `IDAKLU` solver built and working as a separate dependency. However, the restoration of the git commits history still remains a pending task.

## Installation 
To build the wheels - 
`python -m build --wheel`
To install the wheels - 
`python -m pip install dist/*.whl`

### Testing with the upstream PyBaMM repo with `pybammsolvers` as a separate dependency.
With the same `venv` or `conda` environment where `pybammsolvers` was installed with the procedures above, you could run the tests in `PyBaMM` by cloning this [PyBaMM branch without IDAKLU](https://github.com/santacodes/PyBaMM/tree/removeidaklu) (Note: This branch is a pure python package and builds with `hatch`).

### Issues with the `git commit history`
I am trying to restore the history of commits for all the files that we would be moving from the PyBaMM repo to the pybammsolvers repo, the problem is mostly with git as recently we moved to the src layout in PyBaMM which basically means the files that were previously under `pybamm/solvers` are now under `src/pybamm/solvers`, implying that the files were removed from the first path and added to the second path so locally trying to filter out commits didn't work as only the commits from after the `src/` layout move was getting restored, I am not sure why this happens but my best guess would be when you move a file git interprets it as the file was deleted from the original path and a new file was created in the new path. While GitHub shows the previous commit history in a separate hyperlink below the git history page of files, this doesn't happen locally when I `git log -- /src/solvers`. Also, I am prioritising this commit history restoration work because I think we should credit the original authors of the files. Also, we would want the git blame working on the new repository.

P.S. I have this issue posted up on StackOverflow. @kratman @agriyakhetarpal I would love to have your input on this as this is kind of the main blockage for me for the past two weeks.

2024-09-25 13:37 UTC, kratman commented
If the git history starts from scratch, I will not be upset. We just have to make sure that we get the latest code from pybamm when we make the switch

2024-09-25 14:03 UTC, kratman commented
@santacodes Have you looked into getting the tests ported over? That is pretty important. Way more important than syncing git history

2024-09-25 14:49 UTC, agriyakhetarpal commented
I know that we have touched on this before, but only briefly – how about bringing the commit history from PyBaMM before the `src/` layout migration, migrating to the `src/` layout again here manually, and then bringing the commit history after the migration? I think it should be doable.

Your question on StackOverflow: https://stackoverflow.com/questions/78976790/how-do-i-restore-commit-history-for-a-specific-file-that-has-been-renamed does not really provide any details, it might be worth updating so that someone experienced with this can answer it.

As for the tests, I guess we should check out the PyBaMM repo in another folder (`actions/checkout` supports multiple checkouts), cd into it, and then run the tests from there. We should check out from both a release tag and the latest commit in the PyBaMM `develop` branch (i.e., to bring in the tip-of-tree testing I mentioned in the `#separate-idaklu` Slack channel), unless there is something better that I'm missing.

2024-09-25 14:59 UTC, kratman commented
> I know that we have touched on this before, but only briefly – how about bringing the commit history from PyBaMM before the `src/` layout migration, migrating to the `src/` layout again here manually, and then bringing the commit history after the migration? I think it should be doable.

Lets not make this too complicated. We can link to the PR that does the switch and not worry too much about the history. We just make sure the code is identical on the day we switch and go from there.

I don't want to see this held up due to minor issues that won't be important in a years time as the IDAKLU code keeps changing. The whole IDAKLU code went through a large refactor recently, so git blame isn't even that useful anyway.

2024-09-25 15:23 UTC, kratman commented on tests/test_dummy.py
> +import numpy as np
There was no reason to import numpy here

2024-09-25 15:36 UTC, kratman requested changes
I put in a few minor comments, I am testing the build now

2024-09-25 15:36 UTC, kratman commented on .gitignore
A lot of the stuff in here that is still from pybamm. Can we just wipe this out and put in only stuff relevant to this repo

2024-09-25 16:37 UTC, agriyakhetarpal commented on .gitignore
@santacodes, you can refer to https://github.com/toptal/gitignore/blob/master/templates/Python.gitignore for this and build up on it as necessary

2024-09-25 17:22 UTC, santacodes commented on .gitignore
I made some changes, does it look good now?

2024-09-25 17:22 UTC, santacodes commented on .gitignore
I think it would be a good idea to set up pre-commit as well.

2024-09-25 17:28 UTC, santacodes commented
> > I know that we have touched on this before, but only briefly – how about bringing the commit history from PyBaMM before the `src/` layout migration, migrating to the `src/` layout again here manually, and then bringing the commit history after the migration? I think it should be doable.
> 
> Lets not make this too complicated. We can link to the PR that does the switch and not worry too much about the history. We just make sure the code is identical on the day we switch and go from there.
> 
> I don't want to see this held up due to minor issues that won't be important in a years time as the IDAKLU code keeps changing. The whole IDAKLU code went through a large refactor recently, so git blame isn't even that useful anyway.

Would it be a good idea to add the original authors of the solver signed as authors/co-authors in the commit where all the files of solvers are being added? [This](https://github.com/pybamm-team/pybammsolvers/pull/3/commits/4949fc8d13819fd76f2cc52783ea693f4e892b22) commit specifically. I think it would be a simple thing to do and that way we wouldn't have to move all of the history of commits.

2024-09-25 17:29 UTC, kratman commented on .gitignore
Yeah I will set up pre-commit in a different PR

2024-09-25 17:32 UTC, kratman commented
@santacodes Don't worry too much about attribution. This is still a PyBaMM team repo and their work is on PyBaMM. Just forget about that for now and lets focus on getting this working

2024-09-25 18:56 UTC, agriyakhetarpal commented
Please hold on with this – I spent a bit of time towards getting the commit history thingy working and it is working as intended; I got it done pretty quickly, actually: I now have a new repository locally that contains the history for all the code under the current `src/pybamm/solvers/` directory. This properly includes the commit in between where we migrated to the `src` layout: [pybamm-team/PyBaMM@`f49189c`](https://github.com/pybamm-team/PyBaMM/commit/f49189c23d1a129d64fc6608f9b4f31a2e7c31f0)

Now that we know how to do this, I'd recommend trying this out, @santacodes:

This is what I did, you may use a similar variation:

1. Install `git-filter-repo` using `pip install git-filter-repo` (the source is at https://github.com/newren/git-filter-repo)

2. Run the following command (here are their [instructions](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html)):

```bash
git filter-repo --path src/pybamm/solvers --path pybamm/solvers \
--path CMakeLists.txt \
--path pyproject.toml --path setup.py --path MANIFEST.in \
--path vcpkg-configuration.json --path vcpkg.json \
--path LICENSE.txt \
--force
```

i.e., to include all the files that have been relevant to the compiled code in any way over the years. You may run the command in a clone of the PyBaMM repo, and once you are done, you can modify the repo's remote to point to a different GitHub repository, and push the changes there. Please feel free to include or exclude any files in this command that I might have missed including or excluding (for example, the C++ code is only in `src/pybamm/solvers/c_solvers/` and not `src/pybamm/solvers/`)

If there are concerns about how this will be factored into a PR, I recommend that @kratman do this in this repository, re-initialising it with the commit history (or just by creating a new repository if needed since this repository isn't being used at all right now). This is a one-time effort that should not take too long.

2024-09-25 19:11 UTC, kratman requested changes
This has problems with its own dependencies. We need to do something about the `idaklu_jax.py` and `idaklu_solver.py` files requiring pybamm. Either that functionality needs to be migrated here as well, or they need to be removed

2024-09-25 19:11 UTC, kratman commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
This library cannot depend on pybamm, otherwise it is a circular dependency

2024-09-25 19:11 UTC, kratman commented on pyproject.toml
> +    "scikit-fem>=8.1.0",
Why do we need this for a dev dependency?

2024-09-25 19:33 UTC, santacodes commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
Yes, this was a hacky fix to get it working which for some reason works without a circular dependency warning, I think migrating the functionalities here might be tricky though as they are part of different parts of code and are not grouped under a single namespace.

2024-09-25 19:38 UTC, kratman commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
Well here is the problem even if a circular dependency was not a major issue: PyBaMM installs IDAKLU, so how can you be certain that your install is working?

2024-09-25 19:40 UTC, agriyakhetarpal commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
Yes, we'll need to drop PyBaMM as a dependency and adjust the relevant code, even if it means adding a few more things to the Python bindings.

2024-09-25 19:44 UTC, santacodes commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
Install pybamm from the branch I put up in the first PR comment, it has no IDAKLU. I made a fresh venv, installed pybamm without idaklu from the branch I mentioned and installed the pybammsolvers wheels in the same venv. That way all the tests pass. If you are still uncertain you could try running this inside a docker container and it would work, I say this because locally I don't install pip packages as system packages globally so there's no pybamm with idaklu available system-wide.

2024-09-25 19:45 UTC, santacodes commented
> Please hold on with this – I spent a bit of time towards getting the commit history thingy working and it is working as intended; I got it done pretty quickly, actually: I now have a new repository locally that contains the history for all the code under the current `src/pybamm/solvers/` directory. This properly includes the commit in between where we migrated to the `src` layout: [pybamm-team/PyBaMM@`f49189c`](https://github.com/pybamm-team/PyBaMM/commit/f49189c23d1a129d64fc6608f9b4f31a2e7c31f0)
> 
> Now that we know how to do this, I'd recommend trying this out, @santacodes:
> 
> This is what I did, you may use a similar variation:
> 
> 1. Install `git-filter-repo` using `pip install git-filter-repo` (the source is at https://github.com/newren/git-filter-repo)
> 
> 2. Run the following command (here are their [instructions](https://htmlpreview.github.io/?https://github.com/newren/git-filter-repo/blob/docs/html/git-filter-repo.html)):
> 
> ```bash
> git filter-repo --path src/pybamm/solvers --path pybamm/solvers \
> --path CMakeLists.txt \
> --path pyproject.toml --path setup.py --path MANIFEST.in \
> --path vcpkg-configuration.json --path vcpkg.json \
> --path LICENSE.txt \
> --force
> ```
> 
> i.e., to include all the files that have been relevant to the compiled code in any way over the years. You may run the command in a clone of the PyBaMM repo, and once you are done, you can modify the repo's remote to point to a different GitHub repository, and push the changes there. Please feel free to include or exclude any files in this command that I might have missed including or excluding (for example, the C++ code is only in `src/pybamm/solvers/c_solvers/` and not `src/pybamm/solvers/`)
> 
> If there are concerns about how this will be factored into a PR, I recommend that @kratman do this in this repository, re-initialising it with the commit history (or just by creating a new repository if needed since this repository isn't being used at all right now). This is a one-time effort that should not take too long.

Thank you for the suggestion, works! 🎉

2024-09-25 19:49 UTC, kratman commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
@santacodes IDAKLU should install from the pypi wheels when you install PyBaMM. I suspect something is wrong

2024-09-25 19:52 UTC, agriyakhetarpal commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
Ah, no – what we mean is that PyBaMM should depend on IDAKLU, not the other way around. The branch that you have added in the PR description does not currently do so. We want users to run `pip install pybamm` in order to get the IDAKLU solver, and not `pip install idaklu` (from here) to get PyBaMM

2024-09-25 20:20 UTC, santacodes commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
Yes I get you guys, currently pybammsolvers depends on pybamm because of some of the functionalities that the solver files use (for example the basemodel inheritance) and pybamm depends on pybammsolvers for the IDAKLU solver. So this makes them interdependent which is hacky and ideally we should get it working without pybamm as a dependency. Either way I am not sure how we would get those functionalities migrated into pybammsolvers or perhaps we could refactor the solver code. The goal is to make pybammsolvers independent of pybamm and pybamm should depend on pybammsolvers.

2024-09-25 20:23 UTC, santacodes commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
As I mentioned above, a lot of the functionalities belong to different namespaces and classes so migration wouldn't be the best way possible imo. It would be like cherry picking only the specific functionalities of code that solver uses from pybamm and including it here, I'm sure there's a better way.

2024-09-25 20:30 UTC, agriyakhetarpal commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
I'm not sure I follow, but the plan is that we should aim for unvendoring the extension module completely – so that the `pybammsolvers` wheel consists of just one shared object and a Python interface to it in the same folder.

2024-09-25 20:32 UTC, santacodes commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
That's a great idea, but would that also mean we keep the `idaklu_solver.py` and `idaklu_jax.py` in the main PyBaMM repo and not move them here?

2024-09-25 20:39 UTC, kratman commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
I think the idea is that this is only for the C++ side. The python code and dependencies should stay with pybamm whenever possible

2024-09-25 20:45 UTC, agriyakhetarpal commented on pyproject.toml
> +dependencies = ["pybamm", "casadi", "jax", "jaxlib"]
I agree. As long as we have a reliable way of testing it with the PyBaMM test suite, we would be fine with a wheel that just contains a shared object

2024-09-26 14:41 UTC, kratman commented
@santacodes I branched off this PR and I solved the circular dependency issues and a few other topics. I will a new PR after I finish implementing some tests. Mine is based on yours so you will still get credit in the git history

2024-10-02 00:26 UTC, kratman commented
@santacodes My PR seems to be working, so I am going to close this one now

2024-10-02 00:26 UTC, closed without merging