feat: migrate to `scikit-build-core`
pybamm-team/pybammsolvers pull request #7
Opened 2024-10-24 02:48 UTC by cringeyburger

This pull request will migrate the build backend from "setuptools" and "wheel" to "scikit-build-core" along will the updated workflows.

2024-10-24 13:45 UTC, kratman requested changes
Partial review

2024-10-24 13:45 UTC, kratman commented on .github/workflows/build_wheels.yml
> +    types: [opened, synchronize, reopened]
This already ran for every PR
```suggestion
  pull_request:
```

2024-10-24 13:45 UTC, kratman commented on CMakeLists.txt
> +  message("it is alr set: ${CASADI_DIR}")
This is not a good message for printing, please clean this up

2024-10-24 13:45 UTC, kratman commented on CMakeLists.txt
> +endif()
We should be consistent about where files are placed whenever possible

2024-10-24 13:45 UTC, kratman commented on FindSUNDIALS.cmake
> +      ${INSTALL_DIR}
```suggestion
	    ${SUNDIALS_ROOT}
            ${INSTALL_DIR}
```

2024-10-24 13:45 UTC, kratman commented on pyproject.toml
> +version = "0.0.1"
Why can't version be dynamic anymore?

2024-10-24 13:45 UTC, kratman commented on pyproject.toml
> +dependencies = ["casadi", "numpy<2.0"]
```suggestion
dependencies = [
    "casadi",
    "numpy<2.0"
]
```

2024-10-24 13:45 UTC, kratman commented on pyproject.toml
> +dev = ["pytest", "scikit-build-core"]
```suggestion
dev = [
    "pytest",
    "scikit-build-core",
]
```

2024-10-24 13:45 UTC, kratman commented on pyproject.toml
Why are we using hatch here when the rest is scikit-build-core?

2024-10-24 13:45 UTC, kratman commented on pyproject.toml
> +path = "README.md"
Same as above

2024-10-24 13:57 UTC, cringeyburger commented on CMakeLists.txt
> +  message("it is alr set: ${CASADI_DIR}")
Oh, I forgot to change this. Thanks

2024-10-24 14:18 UTC, cringeyburger commented on pyproject.toml
> +version = "0.0.1"
The thing is, scikit-build-core has 3 [built-in plugins](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#dynamic-metadata) for dynamic metadata. 
The one used for versioning is `setuptools_scm`, and when I tried using it, it gave out responses similar to: `0.0.1.dev143+81`. I tried tweaking it a bit and I found that we might have to use git tags. So I opted for manual version, instead of dynamic. 
LMK if you are okay with that default scheme, I can change it.

2024-10-24 14:19 UTC, cringeyburger commented on pyproject.toml
scikit-build-core ships with [3 built-in plugins](https://scikit-build-core.readthedocs.io/en/latest/configuration.html#dynamic-metadata) for dynamic metadata. One of them is hatch, and we need to use it if we want a dynamic readme.

2024-10-24 14:20 UTC, cringeyburger commented on pyproject.toml
> +path = "README.md"
As explained above, we need to use hatch if we want a dynamic readme.

2024-11-14 23:29 UTC, agriyakhetarpal commented on pyproject.toml
> +version = "0.0.1"
I'd very much like to use VCS-based versioning (it's better in many scenarios), but better to avoid it in this PR and proceed with the metadata updates later.

2025-05-06 15:25 UTC, kratman commented
I am going to close this for now. It is badly out of date and probably needs to be re-created. None of the tests passed before either

2025-05-06 15:25 UTC, closed without merging